# Generates catgpt_version.hpp with git metadata about the current
# checkout. Designed to be invoked both at configure time (so the
# header exists for the first build) and at the start of every build
# via an ALL custom target (so re-tagging / committing / dirtying the
# tree shows up in the next binary).
#
# Idempotent: the header is rewritten ONLY when its content actually
# changes, so consumers don't recompile on every build.
#
# Required input vars (set via -D on the cmake -P invocation):
#   SOURCE_DIR   - repo root (the dir that contains .git)
#   OUTPUT_FILE  - absolute path to the header to write

if(NOT DEFINED SOURCE_DIR OR NOT DEFINED OUTPUT_FILE)
    message(FATAL_ERROR "GenVersion.cmake: SOURCE_DIR and OUTPUT_FILE must be set")
endif()

set(GIT_HASH        "unknown")
set(GIT_HASH_SHORT  "unknown")
set(GIT_DESCRIBE    "unknown")
set(GIT_BRANCH      "unknown")
set(GIT_COMMIT_DATE "unknown")
set(GIT_DIRTY_BOOL  "false")

find_program(GIT_EXECUTABLE git)
if(GIT_EXECUTABLE AND IS_DIRECTORY "${SOURCE_DIR}/.git")
    execute_process(
        COMMAND ${GIT_EXECUTABLE} -C ${SOURCE_DIR} rev-parse HEAD
        OUTPUT_VARIABLE _hash OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET RESULT_VARIABLE _rc)
    if(_rc EQUAL 0 AND _hash)
        set(GIT_HASH "${_hash}")
        string(SUBSTRING "${_hash}" 0 7 GIT_HASH_SHORT)
    endif()

    execute_process(
        COMMAND ${GIT_EXECUTABLE} -C ${SOURCE_DIR} describe --tags --always --dirty --long
        OUTPUT_VARIABLE _desc OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET RESULT_VARIABLE _rc)
    if(_rc EQUAL 0 AND _desc)
        set(GIT_DESCRIBE "${_desc}")
    endif()

    execute_process(
        COMMAND ${GIT_EXECUTABLE} -C ${SOURCE_DIR} rev-parse --abbrev-ref HEAD
        OUTPUT_VARIABLE _branch OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET RESULT_VARIABLE _rc)
    if(_rc EQUAL 0 AND _branch)
        set(GIT_BRANCH "${_branch}")
    endif()

    execute_process(
        COMMAND ${GIT_EXECUTABLE} -C ${SOURCE_DIR} show -s --date=format:%Y-%m-%d --format=%cd HEAD
        OUTPUT_VARIABLE _cdate OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET RESULT_VARIABLE _rc)
    if(_rc EQUAL 0 AND _cdate)
        set(GIT_COMMIT_DATE "${_cdate}")
    endif()

    execute_process(
        COMMAND ${GIT_EXECUTABLE} -C ${SOURCE_DIR} status --porcelain --untracked-files=no
        OUTPUT_VARIABLE _status OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET RESULT_VARIABLE _rc)
    if(_rc EQUAL 0 AND _status)
        set(GIT_DIRTY_BOOL "true")
    endif()
endif()

# Canonical, human-facing version string. Labeled so the commit hash is
# obvious wherever the engine identifies itself, e.g.
#   commit 289e575 (2026-06-21)
#   commit 289e575-dirty (2026-06-21)   (uncommitted changes present)
if(GIT_HASH STREQUAL "unknown")
    set(VERSION_STRING "nogit build")
else()
    set(_dirty "")
    if(GIT_DIRTY_BOOL)
        set(_dirty "-dirty")
    endif()
    set(VERSION_STRING "commit ${GIT_HASH_SHORT}${_dirty} (${GIT_COMMIT_DATE})")
endif()

set(_content
"// Auto-generated by cpp/cmake/GenVersion.cmake. Do not edit.
//
// Embeds the git state of the source tree this binary was built from.
// Printed by lks_uci on startup and by trt_benchmark in its header.
#pragma once

namespace catgpt::version {

inline constexpr const char* GIT_HASH        = \"${GIT_HASH}\";
inline constexpr const char* GIT_HASH_SHORT  = \"${GIT_HASH_SHORT}\";
inline constexpr const char* GIT_DESCRIBE    = \"${GIT_DESCRIBE}\";
inline constexpr const char* GIT_BRANCH      = \"${GIT_BRANCH}\";
inline constexpr const char* GIT_COMMIT_DATE = \"${GIT_COMMIT_DATE}\";
inline constexpr bool        GIT_DIRTY       = ${GIT_DIRTY_BOOL};

// Canonical labeled version string, e.g. \"commit 289e575 (2026-06-21)\".
inline constexpr const char* VERSION_STRING  = \"${VERSION_STRING}\";

}  // namespace catgpt::version
")

set(_existing "")
if(EXISTS "${OUTPUT_FILE}")
    file(READ "${OUTPUT_FILE}" _existing)
endif()

if(NOT _existing STREQUAL _content)
    get_filename_component(_outdir "${OUTPUT_FILE}" DIRECTORY)
    file(MAKE_DIRECTORY "${_outdir}")
    file(WRITE "${OUTPUT_FILE}" "${_content}")
    message(STATUS "GenVersion: ${OUTPUT_FILE} updated (${GIT_DESCRIBE})")
endif()
